name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build
        env:
          PORT: 8081
          BASE_PATH: /
          VITE_API_URL: https://sone-gems-backend.onrender.com
          VITE_GOOGLE_CLIENT_ID: 897084071421-bjqcfud9uhs25upfjvn8sibhbc8j16n0.apps.googleusercontent.com

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public
          cname: sonegems.store
